# Generated by Django 3.1.5 on 2021-01-12 16:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20201220_1848"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="nr_views",
            field=models.IntegerField(default=0),
        ),
    ]
