# Generated by Django 3.1.5 on 2021-01-21 18:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee", models.TextField(blank=True, null=True)),
                ("final_coefficient", models.IntegerField(default=0)),
                ("plan_сoefficient", models.IntegerField(default=0)),
                ("quality_сoefficient", models.IntegerField(default=0)),
            ],
        ),
    ]
