# Generated by Django 3.1.5 on 2021-02-06 16:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("KPI", "0004_kpi_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpi",
            name="month",
            field=models.TextField(blank=True, null=True),
        ),
    ]
