# Generated by Django 3.1.5 on 2021-02-07 06:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("KPI", "0007_auto_20210206_2050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpi",
            name="month",
            field=models.IntegerField(
                choices=[
                    [1, "Январь"],
                    [2, "Февраль"],
                    [3, "Март"],
                    [4, "Апрель"],
                    [5, "Май"],
                    [6, "Июнь"],
                    [7, "Июль"],
                    [8, "Август"],
                    [9, "Сентябрь"],
                    [10, "Октябрь"],
                    [11, "Ноябрь"],
                    [12, "Декабрь"],
                ],
                default=1,
            ),
        ),
    ]
