# Generated by Django 3.1.5 on 2021-02-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("KPI", "0008_auto_20210207_0957"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kpi",
            name="month",
        ),
    ]
