# Generated by Django 3.1.3 on 2020-12-01 17:33

import datetime

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 1, 17, 33, 56, 917261, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="nr_like",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
