# Generated by Django 3.1.3 on 2020-12-01 18:46

import datetime

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20201201_2033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 1, 18, 46, 33, 978014, tzinfo=utc)
            ),
        ),
    ]
