# Generated by Django 3.1.3 on 2020-12-01 18:51

from django.db import migrations
from django.db import models

import application.blog.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20201201_2146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(default=application.blog.models._now),
        ),
    ]
