# Generated by Django 3.1.3 on 2020-12-08 18:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_auto_20201201_2154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
