# Generated by Django 3.1.3 on 2020-12-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_auto_20201208_2118"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="nr_like",
            new_name="nr_likes",
        ),
    ]
